services:
  procpag:
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fase3net

  autenticacao-db:
    image: postgres:16-alpine
    container_name: autenticacao-db
    environment:
      POSTGRES_DB: autenticacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
    volumes:
      - autenticacao-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autenticacao"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fase3net

  autenticacao-service:
    build:
      context: ./autenticacao/
      dockerfile: Dockerfile
    container_name: autenticacao-service
    depends_on:
      autenticacao-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://autenticacao-db:5432/autenticacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: psql
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      API_SECURITY_TOKEN_SECRET: minha_chave_super_secreta_jwt_123
    networks:
      - fase3net

  pedido-db:
    image: postgres:16-alpine
    container_name: pedido-db
    environment:
      POSTGRES_DB: pedido
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
    volumes:
      - pedido-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pedido"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fase3net

  pedido-service: 
    build:
      context: ./pedido/
      dockerfile: Dockerfile
    container_name: pedido-service
    depends_on:
      pedido-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pedido-db:5432/pedido
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: psql
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      API_SECURITY_TOKEN_SECRET: minha_chave_super_secreta_jwt_123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - fase3net

  pagamento-service:
    build:
      context: ./pagamento/
      dockerfile: Dockerfile
    container_name: pagamento-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      procpag:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_PAGAMENTO_EXTERNO_URL: http://procpag:8089/requisicao
    networks:
      - fase3net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fase3net

  kong:
    image: kong:3.8
    container_name: gateway-kong
    depends_on:
      - autenticacao-service
      - pedido-service
      - pagamento-service
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - fase3net

volumes:
  autenticacao-data:
  pedido-data:

networks:
  fase3net: