# ===============================
# IDENTIFICAÇÃO DA APLICAÇÃO
# ===============================
spring.application.name=pedido-service

# ===============================
# CONFIGURAÇÕES DO SERVIDOR WEB
# ===============================
# Porta onde a sua API vai rodar (o padrão é 8080)
server.port=8081
# Prefixo global para todos os seus endpoints (opcional, ex: localhost:8080/api/autenticar)
# server.servlet.context-path=/api 

# ===============================
# CONFIGURAÇÕES DE BANCO DE DADOS
# ===============================
# Exemplo usando PostgreSQL (Altere a URL, usuário e senha para o seu banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/pedido
spring.datasource.username=postgres
spring.datasource.password=psql
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# Mostra as queries SQL no console (ótimo para debugar no ambiente de desenvolvimento)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# Atualiza o esquema do banco de dados automaticamente com base nas suas Entidades 
# (Use 'update' para dev e 'validate' ou 'none' para produção)
spring.jpa.hibernate.ddl-auto=create-drop

# ===============================
# VARIÁVEIS CUSTOMIZADAS (SEGURANÇA / JWT)
# ===============================
# Aquela chave secreta que configuramos na classe TokenService usando o @Value
api.security.token.secret=minha_chave_super_secreta_jwt_123
#TODO: PASSAR CHAVE PARA .ENV

# ===============================
# CONFIGURAÇÕES DO RABBITMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.pedido-criado.exchange=pedido.exchange
app.rabbitmq.pedido-criado.queue=pedido.criado.queue
app.rabbitmq.pedido-criado.routing-key=pedido.criado

app.rabbitmq.pagamento.exchange=pagamento.exchange
app.rabbitmq.pagamento-aprovado.queue=pagamento.aprovado.queue
app.rabbitmq.pagamento-aprovado.routing-key=pagamento.aprovado
app.rabbitmq.pagamento-pendente.queue=pagamento.pendente.queue
app.rabbitmq.pagamento-pendente.routing-key=pagamento.pendente