spring.application.name=pagamento

server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.pagamento.exchange=pagamento.exchange

app.rabbitmq.pagamento-pendente.queue=pagamento.pendente.queue
app.rabbitmq.pagamento-pendente.routing-key=pagamento.pendente

app.rabbitmq.pagamento-aprovado.queue=pagamento.aprovado.queue
app.rabbitmq.pagamento-aprovado.routing-key=pagamento.aprovado

app.rabbitmq.pagamento-rejeitado.queue=pagamento.rejeitado.queue
app.rabbitmq.pagamento-rejeitado.routing-key=pagamento.rejeitado

app.rabbitmq.pedido-criado.exchange=pedido.exchange
app.rabbitmq.pedido-criado.queue=pedido.criado.queue
app.rabbitmq.pedido-criado.routing-key=pedido.criado
